SterlingCollection1/Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SterlingCollection1.Models;

namespace SterlingCollection1.Models
{
    public class Album
    {
        public int Id { get; set; }
        public string AlbumName { get; set; }
        public string Artist { get; set; }
        public string Country { get; set; }
        public string Label { get; set; }
        public string Genre { get; set; }
        public int ReleaseYear { get; set; }
        public string AlbumFormat { get; set; }
        public string FormatDetail { get; set; }
        public string AlbumArt { get; set; }
    }
}

SterlingCollection1/Models/Game.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SterlingCollection1.Models;

namespace SterlingCollection1.Models
{
    public class Game
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Console { get; set; }
        public string Publisher { get; set; }
        public int ReleaseYear { get; set; }
        public string CoverArt { get; set; }
    }
}

SterlingCollection1/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SterlingCollection1.Models;

namespace SterlingCollection1.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Format { get; set; }
        public string Genre { get; set; }
        public string Studio { get; set; }
        public int ReleaseYear { get; set; }
        public string CoverArt { get; set; }
    }
}

SterlingCollection1/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SterlingCollection1.Models;
using SterlingCollection1.DAL;

namespace SterlingCollection1.Controllers
{
    public class AlbumController : Controller
    {
        private IAlbumDAL albumDAL;
        public AlbumController(IAlbumDAL albumDAL)
        {
            this.albumDAL = albumDAL;
        }

        // GET: Albums
        public ActionResult VinylRecords()
        {
            List<Album> records = albumDAL.GetAllAlbums();
            return View("VinylRecords", records);
        }

        // GET: Record
        public ActionResult Album(int recordTag)
        {
            Album record = albumDAL.GetAlbumInfo(recordTag);
            return View("Album", record);
        }
    }
}

SterlingCollection1/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SterlingCollection1.Models;
using SterlingCollection1.DAL;

namespace SterlingCollection1.Controllers
{
    public class GameController : Controller
    {

        private IGameDAL gameDAL;

        public GameController(IGameDAL gameDAL)
        {
            this.gameDAL = gameDAL;
        }

        //GET: GameCategory
        public ActionResult GameCategory()
        {
            List<Game> videoGames = gameDAL.GetAllGames();
            return View("GameCategory", videoGames);
        }

        // GET: VideoGames
        public ActionResult VideoGames(int gameTag)
        {
            Game videoGame = gameDAL.GetGameInfo(gameTag);
            return View("VideoGames", videoGame);
        }


    }
}

SterlingCollection1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SterlingCollection1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View("Index");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SterlingCollection1/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SterlingCollection1.Models;
using SterlingCollection1.DAL;

namespace SterlingCollection1.Controllers
{
    public class MovieController : Controller
    {
        private IMovieDAL movieDAL;
        public MovieController(IMovieDAL movieDAL)
        {
            this.movieDAL = movieDAL;
        }

        // GET: Movies
        public ActionResult Movies()
        {
            List<Movie> movies = movieDAL.GetAllMovies();
            return View("Movies", movies);
        }

        // GET: Movie
        public ActionResult Film(int movieTag)
        {
            Movie film = movieDAL.GetMovieInfo(movieTag);
            return View("Film", film);
        }
    }
}

SterlingCollection1/Views/Album/Album.cshtml
@using SterlingCollection1.Models;
@model Album

@{
    ViewBag.Title = "Album";
}

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="game-info">
                    <img class="album-cover" src=@("../Content/Albums/" + Model.AlbumArt) />
                    <h3>@Model.AlbumName</h3>
                    <h3>@Model.Artist</h3>
                    <h3>@Model.Genre</h3>
                    <h3>@Model.ReleaseYear</h3>
                    <h3>@Model.Label</h3>
                    <h3>@Model.Country</h3>
                    <h3>@Model.AlbumFormat</h3>
                    <h3>@Model.FormatDetail</h3>
                </div>
            </div>
        </div>
    </div>
</div>

SterlingCollection1/Views/Album/VinylRecords.cshtml
@using SterlingCollection1.Models;
@model List<Album>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="record-list-background">
    <div class="container-fluid all-games">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="all-albums-list">
                        <h1>Master Vinyl Album List</h1>
                        <p id="grid-btn">Grid View</p>
                            <div id="master-list">
                                @foreach (Album record in Model)
                                {
                                    int recordTag = @record.Id;
                                    <a class="record-anchor" href="@Url.Action("Album", "Album", new { recordTag = recordTag })">
                                        <h2 class="record-info">@record.AlbumName - @record.Artist</h2>
                                    </a>
                                }
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid grid-view">
        <div class="container">
            <div class="grid-box hidden-box">
                @foreach(Album record in Model)
                {
                    int recordTag = @record.Id;
                    <div class="overlay">
                        <a href="@Url.Action("Album", "Album", new { recordTag = recordTag })">
                            <img title="@record.AlbumName - @record.Artist" class="art-box" src="~/Content/Albums/@record.AlbumArt" />
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>

</div>

<script>
    $('#grid-btn').click(function () {
        $('#grid-btn').toggleClass('grid-btn-active');
        $('.grid-box').toggleClass('album-grid');
        $('#master-list').toggleClass('hidden-box');
    });
</script>

SterlingCollection1/Views/Game/GameCategory.cshtml
@using SterlingCollection1.Models;
@using System.Web.Script.Serialization;
@model List<Game>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    string output = new JavaScriptSerializer().Serialize(Model);
}

<audio id="secret-code">
    <source src="~/Content/Other/Zelda.mp3" type="audio/mpeg" />
</audio>

<div class="list-background">
    <div class="container-fluid all-games">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="all-games-list">
                        <h1>Master Game List</h1>
                        <p class="side-nav-btn">Filter</p>
                        @foreach(Game videogame in Model)
                        {
                            int gameTag = @videogame.Id;
                            <a href="@Url.Action("VideoGames", "Game", new { gameTag = gameTag })">
                                <h2 class="@videogame.Console game-name">@videogame.Name</h2>
                            </a>
                        }
                    </div>
                </div>
                @*<div class="col-md-4">
                    <form class="search-form">
                        <input type="text" class="search" placeholder="Enter a Game" />
                        <ul class="suggestions">
                            <li>Filter for a title</li>
                        </ul>
                    </form>
                </div>*@
            </div>
        </div>
    </div>
</div>

<div class="side-nav">
    <div class="button-box">
        <p class="filter-option" id="close-side"><<<</p>
        <p class="filter-option" id="NES">Nintendo Entertainment System</p>
        <p class="filter-option" id="SNES">Super Nintendo</p>
        <p class="filter-option" id="N64">Nintendo 64</p>
        <p class="filter-option" id="GameBoy">Gameboy</p>
        <p class="filter-option" id="GameCube">Gamecube</p>
        <p class="filter-option" id="GBA">Gameboy Advance</p>
        <p class="filter-option" id="DS">Nintendo DS</p>
        <p class="filter-option" id="3DS">Nintendo 3DS</p>
        <p class="filter-option" id="Wii">Wii</p>
        <p class="filter-option" id="Wiiu">Wii U</p>
        <p class="filter-option" id="PS1">Playstation</p>
        <p class="filter-option" id="PS2">Playstation 2</p>
        <p class="filter-option" id="PS3">Playstation 3</p>
        <p class="filter-option" id="PS4">Playstation 4</p>
        <p class="filter-option" id="Vita">Playstation Vita</p>
        <p class="filter-option" id="Genesis">Sega Genesis</p>
        <p class="filter-option" id="Dreamcast">Sega Dreamcast</p>
        <p class="filter-option" id="Xbox">Xbox</p>
        <p class="filter-option" id="360">Xbox 360</p>
        <p class="filter-option" id="XBOne">Xbox One</p>
        <p class="filter-option" id="remove-btn">Remove All Filters</p>
    </div>
</div>

<script src="~/Scripts/Konami.js"></script>

SterlingCollection1/Views/Game/VideoGames.cshtml
@using SterlingCollection1.Models;
@model Game

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="container">
        <div class="game-info">
            <img src=@("../Content/Games/" + Model.CoverArt) />
            <h1>@Model.Name</h1>
            <h3>@Model.Console</h3>
            <h3>@Model.ReleaseYear</h3>
            <h3>@Model.Publisher</h3>
        </div>
    </div>
</div>

SterlingCollection1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<div class="home-background">
    <div class="container-fluid">
        <div class="container home-container home-main">
            <h1>The Sterling Collection</h1>
            <p>The Sterling Collection contains a vast array of electronic media that I have collected over the years.  The collection consists primarily of video games, music, and movies, but also has some other treasures as well.</p>
        </div>
    </div>
</div>

SterlingCollection1/Views/Movie/Film.cshtml
@using SterlingCollection1.Models;
@model Movie

@{
    ViewBag.Title = "Album";
}

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="game-info">
                    <img class="album-cover" src=@("../Content/Movies/" + Model.CoverArt) />
                    <h3>@Model.Name</h3>
                    <h3>@Model.Studio</h3>
                    <h3>@Model.Genre</h3>
                    <h3>@Model.ReleaseYear</h3>
                    <h3>@Model.Format</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/Movies.js"></script>

SterlingCollection1/Views/Movie/Movies.cshtml
@using SterlingCollection1.Models;
@model List<Movie>

@{
    ViewBag.Title = "Movies";
}

<div class="movie-list-background">
    <div class="container-fluid all-movies">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="all-movies-list">
                        <h1>Master Film List</h1>
                        <div id="movie-list">
                            <form class="movie-search-form">
                                <input type="text" class="movie-search" placeholder="Enter a Movie" />
                                <ul class="movie-suggestions">
                                    <li>Filter for a title</li>
                                </ul>
                            </form>
                            @*@foreach (Movie movie in Model)
                            {
                                int movieTag = @movie.Id;
                                <a class="movie-anchor" href="@Url.Action("Film", "Movie", new { movieTag = movieTag })">
                                    <h2 class="movie-info">@movie.Name</h2>
                                </a>
                            }*@
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/Movies.js"></script>

SterlingCollection1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - The Sterling Collection</title>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    @*<script src="~/Scripts/jquery.validate.min.js" defer></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" defer></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js" defer></script>*@
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" defer></script>
    <script src="~/Scripts/VideoGames.js" defer></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Share+Tech+Mono" rel="stylesheet">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
               <a class="navbar-brand" href="#">The Sterling Collection</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Gaming", "GameCategory", "Game")</li>
                <li>@Html.ActionLink("Music", "VinylRecords", "Album")</li>
                <li>@Html.ActionLink("Movies", "Movies", "Movie")</li>
                @*<li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">The Collection
                    <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Games</a></li>
                        <li><a href="#">Music</a></li>
                        <li><a href="#">Movies</a></li>
                    </ul>
                </li>*@
            </ul>
        </div>
    </div>
    <section>
        @RenderBody()
    </section>
</body>
</html>